### ISSUE TITLE
Could not get working

### ISSUE THREAD

**Issue by RichardLitt** [octoherd/script-star-or-unstar#3]
Thoughts? 

Obviously, the token is faulty, too. How do I get an octoherd token? 

```sh
➜  script-star-or-unstar git:(main) npx @octoherd/script-star-or-unstar \
  --octoherd-token 0123456789012345678901234567890123456789 \
  "octoherd/*"
npx: installed 234 in 15.034s
(node:34459) ExperimentalWarning: The ESM module loader is experimental.
file:///Users/richard/.npm/_npx/34459/lib/node_modules/@octoherd/script-star-or-unstar/node_modules/@octoherd/octokit/index.js:4
import { retry } from "@octokit/plugin-retry";
         ^^^^^
SyntaxError: The requested module '@octokit/plugin-retry' does not provide an export named 'retry'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)
    at async Loader.import (internal/modules/esm/loader.js:167:24)
    ```

**Comment by gr2m** [comment]
You need latest Node 12 or 14

**Comment by RichardLitt** [comment]
You're right! Switching to 14 fixed that.

Do I need a particular type of token?

**Comment by RichardLitt** [comment]
Continued story! 

```
➜  script-star-or-unstar git:(main) npx @octoherd/script-star-or-unstar \
  --octoherd-token c3db04... \
  "octoherd/*"
npx: installed 234 in 7.006s

Running @octoherd/cli v2.7.3 (@octoherd/octokit v2.3.1, Node.js: v14.15.5, darwin x64)

 INFO  Loading repositories ...
.
 INFO  Running on octoherd/cli ...
? Do you want to send "PUT https://api.github.com/user/starred/octoherd/cli" Yes
 ERROR  HttpError: Not Found
    at /Users/richard/.npm/_npx/37105/lib/node_modules/@octoherd/script-star-or-unstar/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Job.doExecute (/Users/richard/.npm/_npx/37105/lib/node_modules/@octoherd/script-star-or-unstar/node_modules/bottleneck/light.js:405:18) {"name":"HttpError","status":404,"headers":{"access-control-allow-origin":"*","access-control-expose-headers":"ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval … }

--------------------------------------------------------------------------------

Log file written to /private/var/folders/2z/dlxt5tt50nzdlqlx1qvr1zdm0000gn/T/c4f1bfb9ebc7a822dd968e245e43ab68.ndjson.log
```

**Comment by gr2m** [comment]
Ah yes, i forgot which scope it is but you need an extra one in order to add a star. I’m afk right now I can check it later. 

Eventually scripts should provide which scopes they require, I’m still thinking about how that could work

**Comment by RichardLitt** [comment]
Using "repo" and "user" did it. One may not be needed. Works!
